const axios = require('axios');
const Product = require('../models/Product');
const Supplier = require('../models/Supplier');
const PurchaseRequisition = require('../models/PurchaseRequisition');
const PurchaseOrder = require('../models/PurchaseOrder');
const Truck = require('../models/Truck');
const Invoice = require('../models/Invoice');

const GROK_API_URL = 'https://api.x.ai/v1/chat/completions';

// --- Tool Execution Dispatcher with RBAC ---
const executeTool = async (toolName, params, user) => {
  try {
    const userRole = user?.role || 'guest';

    switch (toolName) {
      case 'createPurchaseRequisition': {
        if (!['procurement_manager', 'admin'].includes(userRole)) {
          return {
            success: false,
            message: `Forbidden: User role '${userRole}' is not authorized to create Purchase Requisitions.`
          };
        }
        const { item, quantity, estimatedPrice } = params;
        const count = await PurchaseRequisition.countDocuments();
        const prNumber = `PR-${1000 + count + 1}`;
        const unitPrice = estimatedPrice || 45;

        const pr = new PurchaseRequisition({
          prNumber,
          requestedBy: user.name || 'AI Assistant',
          items: [{
            productName: item || 'Safety Helmets',
            quantity: Number(quantity || 100),
            estimatedUnitPrice: unitPrice,
            totalPrice: Number(quantity || 100) * unitPrice
          }],
          totalAmount: Number(quantity || 100) * unitPrice,
          aiGenerated: true,
          notes: `Generated by Grok AI for ${user.name}`
        });
        await pr.save();
        return {
          success: true,
          action: 'CREATED_PR',
          prNumber: pr.prNumber,
          details: `Successfully created Purchase Requisition ${pr.prNumber} for ${quantity} x ${item} (Total: \$${pr.totalAmount}).`
        };
      }

      case 'searchSuppliers':
      case 'compareSuppliers': {
        const suppliers = await Supplier.find().sort({ rating: -1, otdScore: -1 }).limit(5);
        return {
          success: true,
          action: 'SUPPLIER_COMPARISON',
          suppliers: suppliers.map(s => ({
            name: s.name,
            code: s.code,
            category: s.category,
            rating: s.rating,
            leadTimeDays: s.leadTimeDays,
            otdScore: `${s.otdScore}%`
          }))
        };
      }

      case 'createPurchaseOrder': {
        if (!['procurement_manager', 'admin'].includes(userRole)) {
          return {
            success: false,
            message: `Forbidden: User role '${userRole}' is not authorized to issue Purchase Orders.`
          };
        }
        const { prNumber, supplierName } = params;
        let pr = await PurchaseRequisition.findOne({ prNumber });
        let supplier = await Supplier.findOne({ name: new RegExp(supplierName || 'Industrial', 'i') });
        if (!supplier) supplier = await Supplier.findOne();

        const count = await PurchaseOrder.countDocuments();
        const poNumber = `PO-${1000 + count + 1}`;
        const items = pr ? pr.items.map(i => ({
          productName: i.productName,
          quantity: i.quantity,
          unitPrice: i.estimatedUnitPrice,
          totalPrice: i.totalPrice
        })) : [{ productName: 'Industrial Goods', quantity: 200, unitPrice: 50, totalPrice: 10000 }];

        const totalAmount = items.reduce((s, i) => s + i.totalPrice, 0);

        const po = new PurchaseOrder({
          poNumber,
          prId: pr ? pr._id : null,
          supplier: supplier._id,
          supplierName: supplier.name,
          items,
          totalAmount,
          status: 'ISSUED'
        });
        await po.save();
        if (pr) await PurchaseRequisition.findByIdAndUpdate(pr._id, { status: 'CONVERTED_TO_PO' });

        return {
          success: true,
          action: 'CREATED_PO',
          poNumber: po.poNumber,
          details: `Created Purchase Order ${po.poNumber} for ${supplier.name} with total \$${totalAmount}.`
        };
      }

      case 'getPurchaseOrder': {
        const { poNumber } = params;
        const po = await PurchaseOrder.findOne({ poNumber: new RegExp(poNumber, 'i') });
        if (!po) return { success: false, message: `PO ${poNumber} not found.` };
        return {
          success: true,
          action: 'PO_STATUS',
          poNumber: po.poNumber,
          status: po.status,
          supplier: po.supplierName,
          amount: po.totalAmount
        };
      }

      case 'getDelayedTrucks': {
        const delayed = await Truck.find({ status: 'DELAYED' });
        return {
          success: true,
          action: 'DELAYED_TRUCKS',
          count: delayed.length,
          trucks: delayed.map(t => ({
            truckId: t.truckId,
            poNumber: t.poNumber,
            eta: t.eta,
            priority: t.priority
          }))
        };
      }

      case 'getInvoiceStatus': {
        const invoices = await Invoice.find().sort({ createdAt: -1 }).limit(5);
        return {
          success: true,
          action: 'INVOICE_STATUS',
          invoices: invoices.map(inv => ({
            invoiceNumber: inv.invoiceNumber,
            poNumber: inv.poNumber,
            supplier: inv.supplierName,
            matchStatus: inv.matchStatus,
            totalAmount: inv.totalAmount
          }))
        };
      }

      default:
        return { success: false, message: 'Unknown tool command' };
    }
  } catch (err) {
    return { success: false, message: err.message };
  }
};

// --- Fallback Intent Parser (Rule-based NLP) ---
const fallbackIntentParser = (message) => {
  const msg = message.toLowerCase();

  if (msg.includes('need') || msg.includes('buy') || msg.includes('order') || msg.includes('requisition') || msg.includes('helmet')) {
    const qtyMatch = msg.match(/\d+/);
    const qty = qtyMatch ? parseInt(qtyMatch[0]) : 100;
    let item = 'Safety Helmet';
    if (msg.includes('glove')) item = 'Work Gloves';
    if (msg.includes('vest')) item = 'Reflective Safety Vest';
    if (msg.includes('boot')) item = 'Steel-Toe Boots';
    if (msg.includes('helmet')) item = 'Safety Helmet';

    return {
      intent: 'create_purchase_requisition',
      tool: 'createPurchaseRequisition',
      params: { item, quantity: qty, estimatedPrice: 45 },
      replyText: `Extracted intent: Create Purchase Requisition for ${qty} x ${item}. Verifying role permissions...`
    };
  }

  if (msg.includes('supplier') || msg.includes('best supplier') || msg.includes('performance') || msg.includes('recommend')) {
    return {
      intent: 'supplier_recommendation',
      tool: 'searchSuppliers',
      params: {},
      replyText: 'Searching and evaluating top suppliers based on rating, OTD score, and lead times...'
    };
  }

  if (msg.includes('po-') || msg.includes('purchase order status') || msg.includes('status of po')) {
    const poMatch = message.match(/PO-\d+/i);
    const poNumber = poMatch ? poMatch[0] : 'PO-1001';
    return {
      intent: 'get_po_status',
      tool: 'getPurchaseOrder',
      params: { poNumber },
      replyText: `Checking live status for Purchase Order ${poNumber}...`
    };
  }

  if (msg.includes('delay') || msg.includes('truck') || msg.includes('where is')) {
    return {
      intent: 'get_delayed_trucks',
      tool: 'getDelayedTrucks',
      params: {},
      replyText: 'Querying yard logistics engine for delayed shipments and truck locations...'
    };
  }

  if (msg.includes('invoice') || msg.includes('pending invoice') || msg.includes('3-way') || msg.includes('match')) {
    return {
      intent: 'get_invoice_status',
      tool: 'getInvoiceStatus',
      params: {},
      replyText: 'Retrieving recent invoices and 3-way match audit records...'
    };
  }

  return {
    intent: 'general_query',
    tool: null,
    params: {},
    replyText: `CogniYard AI Assistant: I can help you create Purchase Requisitions, recommend suppliers, check PO statuses, track delayed trucks, and audit invoices.`
  };
};

exports.chat = async (req, res) => {
  try {
    const { message } = req.body;
    if (!message) {
      return res.status(400).json({ success: false, message: 'Message is required' });
    }

    const apiKey = process.env.XAI_API_KEY;
    let toolResult = null;
    let parsedIntent = null;

    if (apiKey && apiKey !== 'mock_xai_key') {
      try {
        const grokPrompt = `You are CogniYard AI Procurement Assistant. 
Analyze this user request: "${message}"
Identify intent and map to standard tool if applicable:
Available tools:
1. createPurchaseRequisition (params: item, quantity, estimatedPrice)
2. searchSuppliers (params: category)
3. compareSuppliers (params: category)
4. createPurchaseOrder (params: prNumber, supplierName)
5. getPurchaseOrder (params: poNumber)
6. getDelayedTrucks (params: none)
7. getInvoiceStatus (params: none)

Respond ONLY with valid JSON format:
{
  "intent": "<intent_name>",
  "tool": "<tool_name or null>",
  "params": { ... },
  "explanation": "<short natural response>"
}`;

        const response = await axios.post(
          GROK_API_URL,
          {
            model: 'grok-beta',
            messages: [{ role: 'user', content: grokPrompt }],
            temperature: 0.2
          },
          {
            headers: {
              'Authorization': `Bearer ${apiKey}`,
              'Content-Type': 'application/json'
            },
            timeout: 8000
          }
        );

        const content = response.data?.choices?.[0]?.message?.content;
        if (content) {
          const jsonMatch = content.match(/\{[\s\S]*\}/);
          if (jsonMatch) {
            parsedIntent = JSON.parse(jsonMatch[0]);
          }
        }
      } catch (err) {
        console.log('Grok API call fallback activated:', err.message);
      }
    }

    // Fallback parser if Grok API was not used or failed
    if (!parsedIntent) {
      parsedIntent = fallbackIntentParser(message);
    }

    // Execute backend tool with authenticated user context!
    if (parsedIntent.tool) {
      toolResult = await executeTool(parsedIntent.tool, parsedIntent.params || {}, req.user);
    }

    res.json({
      success: true,
      userMessage: message,
      intent: parsedIntent.intent,
      tool: parsedIntent.tool,
      params: parsedIntent.params,
      reply: parsedIntent.explanation || parsedIntent.replyText,
      toolResult
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};
